LD_LIBRARY_PATH: /scratch/rx32940/pop.structure.lepto.int/lineages/7.lineage.dated/Bacterial_Genome_Analysis_Toolbox/resources/mcr/v901/runtime/glnxa64:/scratch/rx32940/pop.structure.lepto.int/lineages/7.lineage.dated/Bacterial_Genome_Analysis_Toolbox/resources/mcr/v901/bin/glnxa64:/scratch/rx32940/pop.structure.lepto.int/lineages/7.lineage.dated/Bacterial_Genome_Analysis_Toolbox/resources/mcr/v901/sys/os/glnxa64
asm_dir: /scratch/rx32940/pop.structure.lepto.int/lineages/7.lineage.dated/Bacterial_Genome_Analysis_Toolbox/../assemblies
biosample_column: 1
define_core: 99
fastGear_exe_path: /scratch/rx32940/pop.structure.lepto.int/lineages/7.lineage.dated/Bacterial_Genome_Analysis_Toolbox/resources/fastGEARpackageLinux64bit/run_fastGEAR.sh
fastGear_params: /scratch/rx32940/pop.structure.lepto.int/lineages/7.lineage.dated/Bacterial_Genome_Analysis_Toolbox/resources/fastGEARpackageLinux64bit/fG_input_specs.txt
fastgear_gene_file_list: ''
gff_dir: null
kingdom: Bacteria
mcr_path: /scratch/rx32940/pop.structure.lepto.int/lineages/7.lineage.dated/Bacterial_Genome_Analysis_Toolbox/resources/mcr/v901/
metadata_include: ''
output: /scratch/rx32940/pop.structure.lepto.int/lineages/7.lineage.dated/Bacterial_Genome_Analysis_Toolbox/results/iqtree/bacterial_analysis.treefile,/scratch/rx32940/pop.structure.lepto.int/lineages/7.lineage.dated/Bacterial_Genome_Analysis_Toolbox/results/gubbins/iqtree/bacterial_analysis.recombFreeSnpsAtcg.treefile,/scratch/rx32940/pop.structure.lepto.int/lineages/7.lineage.dated/Bacterial_Genome_Analysis_Toolbox/results/fastgear_core/plot_coregenome/core_fastgear_plot_recombination_count.pdf,/scratch/rx32940/pop.structure.lepto.int/lineages/7.lineage.dated/Bacterial_Genome_Analysis_Toolbox/results/fastgear_core/fastgear_iqtree/bacterial_analysis_core_mask_snp.treefile,/scratch/rx32940/pop.structure.lepto.int/lineages/7.lineage.dated/Bacterial_Genome_Analysis_Toolbox/results/fastgear_core/plot_coregenome/core_fastgear_plot_recombination_count.pdf
output_dir: /scratch/rx32940/pop.structure.lepto.int/lineages/7.lineage.dated/Bacterial_Genome_Analysis_Toolbox/results
phage_region: null
project_name: bacterial_analysis
reference: ''
sample_metadata: ''
threads_num: 1
