LD_LIBRARY_PATH: /scratch/rx32940/PMEN1/BactPrep/resources/mcr/v901/runtime/glnxa64:/scratch/rx32940/PMEN1/BactPrep/resources/mcr/v901/bin/glnxa64:/scratch/rx32940/PMEN1/BactPrep/resources/mcr/v901/sys/os/glnxa64
asm_dir: /scratch/rx32940/PMEN1/BactPrep/../assemblies
biosample_column: 1
define_core: 99
fastGear_exe_path: /scratch/rx32940/PMEN1/BactPrep/resources/fastGEARpackageLinux64bit/
fastGear_params: /scratch/rx32940/PMEN1/BactPrep/resources/fastGEARpackageLinux64bit/fG_input_specs.txt
fastgear_gene_file_list: ''
gff_dir: /scratch/rx32940/PMEN1/gff
kingdom: Bacteria
mcr_path: /scratch/rx32940/PMEN1/BactPrep/resources/mcr/v901/
metadata_include: ''
output: /scratch/rx32940/PMEN1/fastgear/plot_pangenome/pan_fastgear_plot_recombination_count.pdf
output_dir: /scratch/rx32940/PMEN1
phage_region: ''
project_name: PMEN1.dated
reference: /scratch/rx32940/PMEN1/GCF_000026665.1_ASM2666v1_genomic.fna
sample_metadata: ''
threads_num: 1
