project_name: lept.int.pop.structure
asm_dir: /scratch/rx32940/lept.int.pop.structure/assemblies
gff_dir: /scratch/rx32940/lept.int.pop.structure/gff
output_dir: /scratch/rx32940/lept.int.pop.structure/
fastGear: FALSE
LD_LIBRARY_PATH: /home/rx32940/matlab/v901/runtime/glnxa64:/home/rx32940/matlab/v901/bin/glnxa64:/home/rx32940/matlab/v901/sys/os/glnxa64
fastGear_exe_path: /home/rx32940/SOFTWARE/fastGEARpackageLinux64bit/
mcr_path: /home/rx32940/matlab/v901/
threads_num: 10
kingdom: Bacteria
genus: Leptospira
reference: /scratch/rx32940/lept.int.pop.structure/GCF_000092565.1_ASM9256v1_genomic.fna
phage_region: /scratch/rx32940/lept.int.pop.structure/phage_region.bed
sample_metadata: /scratch/rx32940/lept.int.pop.structure/lept.int.asm.qual.meta.filtered.mutant.filtered.csv
metadata_include: Year,country.1
biosample_column: 1
within_species: TRUE
define_core: 99

