LD_LIBRARY_PATH: /scratch/rx32940/whole_genome/work/2.analysis/BactPrep/resources/mcr/v901/runtime/glnxa64:/scratch/rx32940/whole_genome/work/2.analysis/BactPrep/resources/mcr/v901/bin/glnxa64:/scratch/rx32940/whole_genome/work/2.analysis/BactPrep/resources/mcr/v901/sys/os/glnxa64
asm_dir: /scratch/rx32940/whole_genome/analysis/all_filtered/assemblies
biosample_column: 1
define_core: 99
fastGear_exe_path: /scratch/rx32940/whole_genome/work/2.analysis/BactPrep/resources/fastGEARpackageLinux64bit/
fastGear_params: /scratch/rx32940/whole_genome/work/2.analysis/BactPrep/resources/fastGEARpackageLinux64bit/fG_input_specs.txt
fastgear_gene_file_list: ''
gff_dir: null
gubbins: ''
kingdom: Bacteria
mcr_path: /scratch/rx32940/whole_genome/work/2.analysis/BactPrep/resources/mcr/v901
metadata_include: ''
output: /scratch/rx32940/whole_genome/analysis/all_filtered/gubbins/iqtree/PMEN1.dated.gubbins.treefile
output_dir: /scratch/rx32940/whole_genome/analysis/all_filtered
phage_region: ''
project_name: PMEN1.dated
reference: /scratch/rx32940/whole_genome/ref/GCF_000007685.1_ASM768v1_genomic.fna
roary: ''
sample_metadata: ''
threads_num: 5
