LD_LIBRARY_PATH: /scratch/rx32940/testBactPrep/BactPrep/resources/mcr/v901/runtime/glnxa64:/scratch/rx32940/testBactPrep/BactPrep/resources/mcr/v901/bin/glnxa64:/scratch/rx32940/testBactPrep/BactPrep/resources/mcr/v901/sys/os/glnxa64
asm_dir: /scratch/rx32940/testBactPrep/assemblies
biosample_column: 1
define_core: 99
fastGear_exe_path: /scratch/rx32940/testBactPrep/BactPrep/resources/fastGEARpackageLinux64bit/
fastGear_params: /scratch/rx32940/testBactPrep/BactPrep/resources/fastGEARpackageLinux64bit/fG_input_specs.txt
fastgear_gene_file_list: ''
gff_dir: null
gubbins: ' -f 30'
kingdom: Bacteria
mcr_path: /scratch/rx32940/testBactPrep/BactPrep/resources/mcr/v901
metadata_include: ''
output: /scratch/rx32940/testBactPrep/roary/roary_iqtree/PMEN1.dated.treefile,/scratch/rx32940/testBactPrep/gubbins/iqtree/PMEN1.dated.recombFreeSnpsAtcg.treefile,/scratch/rx32940/testBactPrep/fastgear_core/plot_coregenome/core_fastgear_plot_recombination_count.pdf,/scratch/rx32940/testBactPrep/fastgear_core/fastgear_iqtree/PMEN1.dated_core_mask_snp.treefile,/scratch/rx32940/testBactPrep/fastgear_core/plot_coregenome/core_fastgear_plot_recombination_count.pdf
output_dir: /scratch/rx32940/testBactPrep
phage_region: ''
project_name: PMEN1.dated
reference: /scratch/rx32940/testBactPrep/GCF_000026665.1_ASM2666v1_genomic.fna
roary: ''
sample_metadata: ''
threads_num: 5
