project_name: asia_int_100Core
asm_dir: /scratch/rx32940/asia_int_noOutlier/assemblies
prokka_dir: 
pirate_input: /scratch/rx32940/asia_int_100Core/assemblies
output_dir: /scratch/rx32940/asia_int_100Core/
LD_LIBRARY_PATH: /home/rx32940/matlab/v901/runtime/glnxa64:/home/rx32940/matlab/v901/bin/glnxa64:/home/rx32940/matlab/v901/sys/os/glnxa64
fastGear_exe_path: /home/rx32940/fastGEARpackageLinux64bit/
mcr_path: /home/rx32940/matlab/v901/
threads_num: 10
kingdom: Bacteria
genus: Leptospira
reference: /scratch/rx32940/pathogenic_sero/GCF_000092565.1_ASM9256v1_genomic.fna
phage_region: /scratch/rx32940/pathogenic_sero/snippy/phage_region.bed
within_species: TRUE
define_core: 100
