project_name: baps.lineage.1
asm_dir: /scratch/rx32940/lept.int.geo.pangenome/fastBAPs/BAP.lineages/baps.lineage.1/assemblies
gff_dir: /scratch/rx32940/lept.int.geo.pangenome/fastBAPs/BAP.lineages/baps.lineage.1/gff
pirate_input:
output_dir: /scratch/rx32940/lept.int.geo.pangenome/fastBAPs/BAP.lineages/baps.lineage.1/
LD_LIBRARY_PATH: /home/rx32940/matlab/v901/runtime/glnxa64:/home/rx32940/matlab/v901/bin/glnxa64:/home/rx32940/matlab/v901/sys/os/glnxa64
fastGear_exe_path: /home/rx32940/SOFTWARE/fastGEARpackageLinux64bit/
mcr_path: /home/rx32940/matlab/v901/
threads_num: 10
kingdom: Bacteria
genus: Leptospira
reference: /scratch/rx32940/lept.int.geo.pangenome/fastBAPs/BAP.lineages/baps.lineage.1/assemblies/SAMN02436629.fna
phage_region: 
sample_metadata: /scratch/rx32940/lept.int.geo.pangenome/lepto.int.geo.all.csv
metadata_include: Year,serogroups,country
biosample_column: 1
within_species: TRUE
define_core: 99

