project_name: int_lineage_5_fastbaps
asm_dir: /scratch/rx32940/all_interrogans_dated/assemblies
prokka_dir: 
pirate_input: /scratch/rx32940/all_interrogans_dated/assemblies
output_dir: /scratch/rx32940/int_lineage_5_fastbaps/
LD_LIBRARY_PATH: /home/rx32940/matlab/v901/runtime/glnxa64:/home/rx32940/matlab/v901/bin/glnxa64:/home/rx32940/matlab/v901/sys/os/glnxa64
fastGear_exe_path: /home/rx32940/fastGEARpackageLinux64bit/
mcr_path: /home/rx32940/matlab/v901/
subworkflow: rules/
threads_num: 10
kingdom: Bacteria
genus: Leptospira
reference: /home/rx32940/snakemake_assembly_workdir/GCF_000092565.1_ASM9256v1_genomic.fna
phage_region: /scratch/rx32940/pathogenic_sero/snippy/phage_region.bed
within_species: TRUE
samples:
  SAMN16925409: SRR13255634