LD_LIBRARY_PATH: /home/rx32940/matlab/v901/runtime/glnxa64:/home/rx32940/matlab/v901/bin/glnxa64:/home/rx32940/matlab/v901/sys/os/glnxa64
asm_dir: /scratch/rx32940/pop.structure.lepto.int/lineages/4.lineage/Bacterial_Genome_Analysis_Toolbox/../assemblies
biosample_column: 1
define_core: 99
fastGear_exe_path: /home/rx32940/SOFTWARE/fastGEARpackageLinux64bit/
fastgear_gene_file_list: ''
genus: Leptospira
gff_dir: null
kingdom: Bacteria
mcr_path: /home/rx32940/matlab/v901/
metadata_include: ''
output: /scratch/rx32940/pop.structure.lepto.int/lineages/4.lineage/fastgear_core/plot_coregenome/core_fastgear_plot_recombination_count.pdf,/scratch/rx32940/pop.structure.lepto.int/lineages/4.lineage/fastgear_core/fastgear_iqtree/pop.struc.lineage.4_core_mask_snp.treefile
output_dir: /scratch/rx32940/pop.structure.lepto.int/lineages/4.lineage
phage_region: null
project_name: pop.struc.lineage.4
reference: ''
sample_metadata: ''
threads_num: 1
