LD_LIBRARY_PATH: /home/rx32940/matlab/v901/runtime/glnxa64:/home/rx32940/matlab/v901/bin/glnxa64:/home/rx32940/matlab/v901/sys/os/glnxa64
asm_dir: /scratch/rx32940/pop.structure.lepto.int/lineages/4.lineage/assemblies
biosample_column: 1
define_core: 99
fastGear_exe_path: /home/rx32940/SOFTWARE/fastGEARpackageLinux64bit/
fastGear_params: /home/rx32940/SOFTWARE/fastGEARpackageLinux64bit/fG_input_specs.txt
fastgear_gene_file_list: ''
genus: Leptospira
gff_dir: null
kingdom: Bacteria
mcr_path: /home/rx32940/matlab/v901/
metadata_include: ''
output: /scratch/rx32940/pop.structure.lepto.int/lineages/4.lineage/iqtree/pop.struc.lineage.4.treefile,/scratch/rx32940/pop.structure.lepto.int/lineages/4.lineage/gubbins/iqtree/pop.struc.lineage.4.recombFreeSnpsAtcg.treefile,/scratch/rx32940/pop.structure.lepto.int/lineages/4.lineage/fastgear_core/plot_coregenome/core_fastgear_plot_recombination_count.pdf,/scratch/rx32940/pop.structure.lepto.int/lineages/4.lineage/fastgear_core/fastgear_iqtree/pop.struc.lineage.4_core_mask_snp.treefile,/scratch/rx32940/pop.structure.lepto.int/lineages/4.lineage/fastgear_core/plot_coregenome/core_fastgear_plot_recombination_count.pdf
output_dir: /scratch/rx32940/pop.structure.lepto.int/lineages/4.lineage
phage_region: /scratch/rx32940/pop.structure.lepto.int/phage_region.bed
project_name: pop.struc.lineage.4
reference: /scratch/rx32940/pop.structure.lepto.int/GCF_000092565.1_ASM9256v1_genomic.fna
sample_metadata: ''
threads_num: 10
